# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdfb2f7cc376f9d5bc94265a57034f35496c13ffbbd3229e6bdc42e0ec12b9b0125f6fb4b03f623df580c9cd33e38528f932c5f31925de984dbaa87ac5bbd0a3

test:
  secret_key_base: d799702dbc312d2bbc3a7b1059d2de3842006626af5a6aa6bf77e8fc13ea02d34848c8a877f5b00b6b3fb71fb83f05b5800f0ba86a29b7b6228fe3914c06e7b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
